-- Exercise 3k
CREATE TABLE R (A INT, B INT, C, INT, D INT, E INT, F INT);
CREATE TABLE F (x VARCHAR(10), y VARCHAR(10), violation INT, motivation VARCHAR(400));
-- Exercise 3l
CREATE TABLE R1 (D INT, E INT);
CREATE TABLE R2 (A INT, B INT, C, INT, E INT, F INT);
CREATE TABLE F1 (x VARCHAR(10), y VARCHAR(10), violation INT, motivation VARCHAR(400));
CREATE TABLE F2 (x VARCHAR(10), y VARCHAR(10), violation INT, motivation VARCHAR(400));



